Features
WESTnik/python-SSL-checker pull request #1
Opened 2021-12-14 14:49 UTC by WESTnik

Create main project and documentation.

2021-12-15 08:35 UTC, abystrov requested changes

2021-12-15 08:35 UTC, abystrov commented on README.md
> +Function * *"def check_cert_validity()"* * used for validate SSL certificate on site. Required function argument is SSL certificate. Returned function value is "TRUE" or "FALSE"
Functions description is better to keep in code rather than in readme. It will be easier to read your code

2021-12-15 08:35 UTC, abystrov commented on ssl_checker.py
> +DAYS_TO_EXPIRATION = 50
It would be nice to get value for this variable from arguments

2021-12-15 08:35 UTC, abystrov commented on ssl_checker.py
> +        print(f'Unknown host: {target_url}')
Try to use logging library instead of printing

2021-12-15 12:19 UTC, abstractsage commented on README.md
> +### Requirements
Requirements should be also listed in a separated files requirements.txt
Check pip freeze command

2021-12-15 12:23 UTC, abstractsage commented on README.md
> +def check_cert_validity(cert: Dict) -> bool:
It's a good practise to specify types of key / value inside a dict, f.e. Dict[str, str]

2021-12-15 12:25 UTC, abstractsage commented on ssl_checker.py
> +from typing import Dict, Union
Imports should be grouped in the following order:
Standard library imports.
Related third party imports.
Local application/library specific imports.
You should put a blank line between each group of imports.

Also it's a good practise to group imports im alphabet order per such a block

2021-12-15 12:25 UTC, abstractsage commented on ssl_checker.py
> +def check_cert_validity(cert: Dict) -> bool:
missed docstrings

2021-12-15 12:26 UTC, abstractsage commented on ssl_checker.py
> +def check_cert_validity(cert: Dict) -> bool:
also, it's a good practise to specify types of k/v pairs inside a dict, f.e. Dict[str, str]

2021-12-15 12:30 UTC, abstractsage commented on ssl_checker.py
> +def get_ssl_cert(target_url: str) -> Union[Dict, None]:
It's actually great that you know how to use socket library, but it's to low level, for HTTP requests it's better to use requests library, which is the most popular python module and it's good to know it too.

2021-12-15 12:32 UTC, abstractsage commented on ssl_checker.py
> +def str_to_date(date_string: str) -> datetime:
missed docstrings

2021-12-16 15:01 UTC, abystrov approved these changes

2021-12-17 08:33 UTC, merged